soda_cloud:
  host: cloud.us.soda.io
  api_key_id: fc603374-335d-4aa8-830c-1b8e03cd217c
  api_key_secret: 6yr06GvHjtq0Ch6bQC3nqzg5PP7F6nZQJxdS_hpxBMwWujcUb6K-tQ
data_source adventureworks:
  type: postgres
  connection:
    host: localhost
    username: postgres
    password: secret
    database: postgres
    schema: public